
# dac8x_streamer_44c_192p_tone_80Hz.yml
# Variant: Bass shelf at 80 Hz (vs 90 Hz), everything else identical

title: "DAC8x Streamer 44c → 192p + Tone (80Hz Bass)"
description: "Same as tone preset, but lowshelf bass pivot at 80 Hz."

devices:
  samplerate: 192000
  chunksize: 4096
  capture:
    type: Alsa
    channels: 2
    device: "hw:Loopback,1"   # adjust to your system
    format: S32LE
  playback:
    type: Alsa
    channels: 8
    device: "hw:0,0"          # adjust to your DAC8x device
    format: S32LE
  enable_rate_adjust: false
  capture_samplerate: 44100

resampler:
  type: SincBest
  parameters:
    passband_end: 0.98
    stopband_begin: 1.02

mixers:
  to8:
    description: "Expand 2 channels (L/R) to 8 outputs for DAC8x"
    channels: { in: 2, out: 8 }
    mapping:
      - { dest: 0, sources: [ { channel: 0, gain: 0.0, inverted: false } ] }
      - { dest: 1, sources: [ { channel: 1, gain: 0.0, inverted: false } ] }
      - { dest: 2, sources: [ { channel: 0, gain: 0.0, inverted: false } ] }
      - { dest: 3, sources: [ { channel: 1, gain: 0.0, inverted: false } ] }
      - { dest: 4, sources: [ { channel: 0, gain: 0.0, inverted: false } ] }
      - { dest: 5, sources: [ { channel: 1, gain: 0.0, inverted: false } ] }
      - { dest: 6, sources: [ { channel: 0, gain: 0.0, inverted: false } ] }
      - { dest: 7, sources: [ { channel: 1, gain: 0.0, inverted: false } ] }

filters:
  # Channel 0
  Bass_0:   { type: Biquad, parameters: { type: Lowshelf,  freq: 80,   q: 0.9, gain: 0.0 } }
  Mid_0:    { type: Biquad, parameters: { type: Peaking,   freq: 1000, q: 1.0, gain: 0.0 } }
  Treble_0: { type: Biquad, parameters: { type: Highshelf, freq: 6500, q: 0.7, gain: 0.0 } }
  # Channel 1
  Bass_1:   { type: Biquad, parameters: { type: Lowshelf,  freq: 80,   q: 0.9, gain: 0.0 } }
  Mid_1:    { type: Biquad, parameters: { type: Peaking,   freq: 1000, q: 1.0, gain: 0.0 } }
  Treble_1: { type: Biquad, parameters: { type: Highshelf, freq: 6500, q: 0.7, gain: 0.0 } }
  # Channel 2
  Bass_2:   { type: Biquad, parameters: { type: Lowshelf,  freq: 80,   q: 0.9, gain: 0.0 } }
  Mid_2:    { type: Biquad, parameters: { type: Peaking,   freq: 1000, q: 1.0, gain: 0.0 } }
  Treble_2: { type: Biquad, parameters: { type: Highshelf, freq: 6500, q: 0.7, gain: 0.0 } }
  # Channel 3
  Bass_3:   { type: Biquad, parameters: { type: Lowshelf,  freq: 80,   q: 0.9, gain: 0.0 } }
  Mid_3:    { type: Biquad, parameters: { type: Peaking,   freq: 1000, q: 1.0, gain: 0.0 } }
  Treble_3: { type: Biquad, parameters: { type: Highshelf, freq: 6500, q: 0.7, gain: 0.0 } }
  # Channel 4
  Bass_4:   { type: Biquad, parameters: { type: Lowshelf,  freq: 80,   q: 0.9, gain: 0.0 } }
  Mid_4:    { type: Biquad, parameters: { type: Peaking,   freq: 1000, q: 1.0, gain: 0.0 } }
  Treble_4: { type: Biquad, parameters: { type: Highshelf, freq: 6500, q: 0.7, gain: 0.0 } }
  # Channel 5
  Bass_5:   { type: Biquad, parameters: { type: Lowshelf,  freq: 80,   q: 0.9, gain: 0.0 } }
  Mid_5:    { type: Biquad, parameters: { type: Peaking,   freq: 1000, q: 1.0, gain: 0.0 } }
  Treble_5: { type: Biquad, parameters: { type: Highshelf, freq: 6500, q: 0.7, gain: 0.0 } }
  # Channel 6
  Bass_6:   { type: Biquad, parameters: { type: Lowshelf,  freq: 80,   q: 0.9, gain: 0.0 } }
  Mid_6:    { type: Biquad, parameters: { type: Peaking,   freq: 1000, q: 1.0, gain: 0.0 } }
  Treble_6: { type: Biquad, parameters: { type: Highshelf, freq: 6500, q: 0.7, gain: 0.0 } }
  # Channel 7
  Bass_7:   { type: Biquad, parameters: { type: Lowshelf,  freq: 80,   q: 0.9, gain: 0.0 } }
  Mid_7:    { type: Biquad, parameters: { type: Peaking,   freq: 1000, q: 1.0, gain: 0.0 } }
  Treble_7: { type: Biquad, parameters: { type: Highshelf, freq: 6500, q: 0.7, gain: 0.0 } }

pipeline:
  - { type: Mixer, name: to8 }
  - { type: Filter, channel: 0, names: [Bass_0, Mid_0, Treble_0] }
  - { type: Filter, channel: 1, names: [Bass_1, Mid_1, Treble_1] }
  - { type: Filter, channel: 2, names: [Bass_2, Mid_2, Treble_2] }
  - { type: Filter, channel: 3, names: [Bass_3, Mid_3, Treble_3] }
  - { type: Filter, channel: 4, names: [Bass_4, Mid_4, Treble_4] }
  - { type: Filter, channel: 5, names: [Bass_5, Mid_5, Treble_5] }
  - { type: Filter, channel: 6, names: [Bass_6, Mid_6, Treble_6] }
  - { type: Filter, channel: 7, names: [Bass_7, Mid_7, Treble_7] }
